### ISSUE TITLE
module "impacket.dcerpc.v5.nrpc" has no attribute "NetrServerPasswordSet2"

### ISSUE THREAD

**Issue by ozltr** [risksense/zerologon#7]
Hi!

The title shows every time I run the "set_empty_pw.py" script, but right after the 'error' your script says: "success! dc should now have the empty string as its machine password". But btw, it doesn't!

I've reinstalled impacket, with 
"pip3 install impacket"
downloaded the impacket repo from [source](https://github.com/SecureAuthCorp/impacket)
"python3.6 setup.py install"
"python3.6 setup.py build"
"sudo apt install python-impacket"
I've tried to change all the "#!/usr/bin/env <python versions differ here>" to "!/usr/bin/python3.6"
and the script keep complaining on that "has no attribute". I wrote a python3.6 script using NetrServerPasswordSet2 and then it doesn't get error.

**Comment by D4rkC0m3t** [comment]
Hi There,

I`m facing the below issue please provide fix for this 

Traceback (most recent call last):
  File "set_empty_pw.py", line 3, in <module>
    from impacket.dcerpc.v5 import nrpc, epm
ModuleNotFoundError: No module named 'impacket.dcerpc'

**Comment by Aareon** [comment]
> Hi!
> 
> The title shows every time I run the "set_empty_pw.py" script, but right after the 'error' your script says: "success! dc should now have the empty string as its machine password". But btw, it doesn't!
> 
> I've reinstalled impacket, with
> "pip3 install impacket"
> downloaded the impacket repo from [source](https://github.com/SecureAuthCorp/impacket)
> "python3.6 setup.py install"
> "python3.6 setup.py build"
> "sudo apt install python-impacket"
> I've tried to change all the "#!/usr/bin/env " to "!/usr/bin/python3.6"
> and the script keep complaining on that "has no attribute". I wrote a python3.6 script using NetrServerPasswordSet2 and then it doesn't get error.

You should use a virtual environment.
Make sure you’re using Python 3.6+
```
cd zerologon/
python3 -m venv venv
./venv/Scripts/activate
```
Ensure the env is active
`python3 --version`
`pip install impacket` just in-case venv doesn’t work, use `--user`

`python3 setup.py install`

**Comment by Aareon** [comment]
> Hi There,
> 
> I`m facing the below issue please provide fix for this
> 
> Traceback (most recent call last):
> File "set_empty_pw.py", line 3, in 
> from impacket.dcerpc.v5 import nrpc, epm
> ModuleNotFoundError: No module named 'impacket.dcerpc'

Follow the same instructions in my previous comment
